spring.application.name=SpringToDatabase_JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=postgres
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=non

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always


# Enable fine-grained debugging logs for all Spring Security internal logic
logging.level.org.springframework.security=DEBUG

# Enable logging for web request mapping routines
logging.level.org.springframework.web=DEBUG

# Optional: View exactly what values Hibernate is binding to your SQL queries
logging.level.org.hibernate.orm.jdbc.bind=TRACE


jwt.secrete=slvdsvhdvhkhvgyyueojoihskbhjbzvuhsbbsgsfehgdbsnnjjksjsjisjnn
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
